### ISSUE TITLE
Bad tenant URI 

### ISSUE THREAD

**Issue by RalfZi** [mwittrock/cpilint#15]
Hello I use CPILINT for the first time. Since I am working behind a firewall I had to add the following parameters to the cpilint.bat
`"%JAVACMD%"%ASSERTS% -Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128 -classpath "%CPILINT_CP%" dk.mwittrock.cpilint.CliClient %*`

Now wen I run it I get the error **Bad tenant URI** 
is the Command line parameter wrong?
`-host https://trial-3nudqf4g.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com `
see logs:

```
07:23:28.231 INFO  dk.mwittrock.cpilint.CliClient - CPILint version 1.0.4
07:23:28.264 INFO  dk.mwittrock.cpilint.CliClient - Launching CliClient
07:23:28.264 DEBUG dk.mwittrock.cpilint.CliClient - Command line arguments provided: '-rules' '../samples/naming.xml' '-host' 'https://trial-3nudqf4g.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com' '-user' 'ralf.zimmerningkat@svlfg.de' '-password' '*******' '-debug'
07:23:28.264 INFO  dk.mwittrock.cpilint.CliClient - Command line arguments parsed successfully
07:23:28.264 INFO  dk.mwittrock.cpilint.CliClient - Mode detected: TENANT_SUPPLIER_MULTI_MODE
07:23:28.512 INFO  dk.mwittrock.cpilint.RulesFile - Rules file XML is valid
07:23:29.112 DEBUG dk.mwittrock.cpilint.CliClient - Calling GitHub API at https://api.github.com/repos/mwittrock/cpilint/releases/latest
07:23:29.945 DEBUG dk.mwittrock.cpilint.CliClient - Parsing GitHub API response
07:23:29.945 DEBUG dk.mwittrock.cpilint.CliClient - Extracted tag 'v1.0.4' from GitHub API response
07:23:29.945 DEBUG dk.mwittrock.cpilint.CliClient - The latest version on GitHub is 1.0.4
07:23:29.945 INFO  dk.mwittrock.cpilint.CpiLint - Starting inspection of iflow artifacts
07:23:29.945 INFO  d.m.c.api.CloudIntegrationOdataApi - Retrieving package IDs from tenant
07:23:29.945 DEBUG d.m.c.api.CloudIntegrationOdataApi - SAP packages will be included
07:23:30.179 ERROR dk.mwittrock.cpilint.CliClient - Iflow artifact supplier error
dk.mwittrock.cpilint.suppliers.IflowArtifactSupplierError: API error when fetching package IDs
	at dk.mwittrock.cpilint.suppliers.TenantAllArtifactsSupplier.setup(Unknown Source)
	at dk.mwittrock.cpilint.CpiLint.run(Unknown Source)
	at dk.mwittrock.cpilint.CliClient.main(Unknown Source)
Caused by: dk.mwittrock.cpilint.api.CloudIntegrationApiError: Bad tenant URI error
	at dk.mwittrock.cpilint.api.CloudIntegrationOdataApi.tenantUriFromPath(Unknown Source)
	at dk.mwittrock.cpilint.api.CloudIntegrationOdataApi.integrationPackagesUri(Unknown Source)
	at dk.mwittrock.cpilint.api.CloudIntegrationOdataApi.getEditableIntegrationPackageIds(Unknown Source)
	... 3 common frames omitted
Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 15: https://[https://trial-3nudqf4g.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com]/api/v1/IntegrationPackages
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.failExpecting(Unknown Source)
	at java.base/java.net.URI$Parser.parseServer(Unknown Source)
	at java.base/java.net.URI$Parser.parseAuthority(Unknown Source)
	at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	... 6 common frames omitted
07:23:30.179 INFO  dk.mwittrock.cpilint.CliClient - Exiting CliClient with error status 2 and message: There was an error while retrieving iflow artifacts: API error when fetching package IDs
```

regards
Ralf

**Comment by mwittrock** [comment]
Hi Ralf

In addition to your question, you raise a good point about dealing with local HTTP proxies. This might be something that should at least be added to the documentation, if not supported directly by the tool.

About the -host parameter. First off, it excepts only the hostname, not a URL. so remove the "https://" bit. Second, what you need is not the hostname of the Integration Suite application, but rather the so-called _service root_ of the Cloud Integration OData API. Where to find it is documented [here](https://help.sap.com/docs/cloud-integration/sap-cloud-integration/http-calls-and-uri-components). But basically you copy it from a service key created with the api plan.

This will be added to an FAQ in the wiki shortly. 

Let me know how it works out!

Regards,

Morten

**Comment by RalfZi** [comment]
Hi Morton
I update the host to
`-host trial-3nudqf4g.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com/api/v1`
now the log shows the error 
**The reference to entity "client_id" must end with the ';' delimiter**

```
08:57:20.758 INFO  dk.mwittrock.cpilint.CliClient - CPILint version 1.0.4
08:57:20.784 INFO  dk.mwittrock.cpilint.CliClient - Launching CliClient
08:57:20.787 DEBUG dk.mwittrock.cpilint.CliClient - Command line arguments provided: '-rules' '../samples/naming.xml' '-host' 'trial-3nudqf4g.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com/api/v1' '-user' 'ralf.zimmerningkat@svlfg.de' '-password' '*******' '-debug'
08:57:20.793 INFO  dk.mwittrock.cpilint.CliClient - Command line arguments parsed successfully
08:57:20.794 INFO  dk.mwittrock.cpilint.CliClient - Mode detected: TENANT_SUPPLIER_MULTI_MODE
08:57:21.038 INFO  dk.mwittrock.cpilint.RulesFile - Rules file XML is valid
08:57:21.761 DEBUG dk.mwittrock.cpilint.CliClient - Calling GitHub API at https://api.github.com/repos/mwittrock/cpilint/releases/latest
08:57:22.426 DEBUG dk.mwittrock.cpilint.CliClient - Parsing GitHub API response
08:57:22.432 DEBUG dk.mwittrock.cpilint.CliClient - Extracted tag 'v1.0.4' from GitHub API response
08:57:22.432 DEBUG dk.mwittrock.cpilint.CliClient - The latest version on GitHub is 1.0.4
08:57:22.433 INFO  dk.mwittrock.cpilint.CpiLint - Starting inspection of iflow artifacts
08:57:22.433 INFO  d.m.c.api.CloudIntegrationOdataApi - Retrieving package IDs from tenant
08:57:22.433 DEBUG d.m.c.api.CloudIntegrationOdataApi - SAP packages will be included
08:57:22.652 DEBUG d.m.c.api.CloudIntegrationOdataApi - Integration packages URI generated: https://trial-3nudqf4g.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com/api/v1/api/v1/IntegrationPackages
08:57:23.103 ERROR dk.mwittrock.cpilint.CliClient - Iflow artifact supplier error
dk.mwittrock.cpilint.suppliers.IflowArtifactSupplierError: API error when fetching package IDs
	at dk.mwittrock.cpilint.suppliers.TenantAllArtifactsSupplier.setup(Unknown Source)
	at dk.mwittrock.cpilint.CpiLint.run(Unknown Source)
	at dk.mwittrock.cpilint.CliClient.main(Unknown Source)
Caused by: dk.mwittrock.cpilint.api.CloudIntegrationApiError: Error evaluating XQuery
	at dk.mwittrock.cpilint.api.CloudIntegrationOdataApi.evaluateXquery(Unknown Source)
	at dk.mwittrock.cpilint.api.CloudIntegrationOdataApi.getApiResponseAndEvaluateXquery(Unknown Source)
	at dk.mwittrock.cpilint.api.CloudIntegrationOdataApi.getEditableIntegrationPackageIds(Unknown Source)
	... 3 common frames omitted
Caused by: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 518; The reference to entity "client_id" must end with the ';' delimiter.
	at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:360)
	at net.sf.saxon.s9api.XQueryEvaluator.setSource(XQueryEvaluator.java:134)
	... 6 common frames omitted
Caused by: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 518; The reference to entity "client_id" must end with the ';' delimiter.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:459)
	at net.sf.saxon.event.Sender.send(Sender.java:168)
	at net.sf.saxon.Configuration.buildDocumentTree(Configuration.java:4201)
	at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:357)
	... 7 common frames omitted
Caused by: org.xml.sax.SAXParseException: The reference to entity "client_id" must end with the ';' delimiter.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:439)
	... 10 common frames omitted
08:57:23.103 INFO  dk.mwittrock.cpilint.CliClient - Exiting CliClient with error status 2 and message: There was an error while retrieving iflow artifacts: API error when fetching package IDs
```
Regards,
Ralf

**Comment by mwittrock** [comment]
Hi Ralf

Sorry, I was not entirely clear. The -host parameter should only contain a hostname, nothing else. CPILint uses that hostname to generate the service root. The hostname you copy from a service key (created with the api plan). Specifically from the "url" field. Do not copy the entire field! Just the hostname.

How to create a service key is described [here](https://help.sap.com/docs/cloud-integration/sap-cloud-integration/creating-service-instance-and-service-key-for-inbound-authentication).

Regards,

Morten

**Comment by RalfZi** [comment]
Hello Morton
I am inconsolable, but I seem to be slow on the uptake today.
My api key is as follows and I am using the url, but I am still getting the same error.

```
{
  "oauth": {
    "createdate": "2024-08-06T07:46:32.897Z",
    "clientid": "xxxxxx",
    "clientsecret": "xxxxx",
    "tokenurl": "https://trial-3nudqf4g.authentication.us10.hana.ondemand.com/oauth/token",
    "url": "https://trial-3nudqf4g.it-cpitrial05.cfapps.us10-001.hana.ondemand.com"
  }
}
```
Ralf

**Comment by mwittrock** [comment]
Hi Ralf

You should not add the whole URL; just the hostname. So your -host parameter should contain: trial-3nudqf4g.it-cpitrial05.cfapps.us10-001.hana.ondemand.com

Regards,

Morten

**Comment by RalfZi** [comment]
I try the generated URL from the log file in my local browser:
https://[trial-3nudqf4g.it-cpitrial05.cfapps.us10-001.hana.ondemand.com/api/v1/IntegrationPackages](https://trial-3nudqf4g.it-cpitrial05.cfapps.us10-001.hana.ondemand.com/api/v1/IntegrationPackages)
so the url seems to be correct
I am unable to pass a password with special characters like % as a parameter  whithout the parameter -password it works

```

<feed xmlns="http://www.w3.org/2005/Atom" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xml:base="https://trial-3nudqf4g.it-cpitrial05.cfapps.us10-001.hana.ondemand.com:443/api/v1/">
<id>https://trial-3nudqf4g.it-cpitrial05.cfapps.us10-001.hana.ondemand.com:443/api/v1/IntegrationPackages</id>
<title type="text">IntegrationPackages</title>
<updated>2024-08-08T07:45:12.669Z</updated>
<author>
<name/>
</author>
<link href="IntegrationPackages" rel="self" title="IntegrationPackages"/>
<entry>
<id>https://trial-3nudqf4g.it-cpitrial05.cfapps.us10-001.hana.ondemand.com:443/api/v1/IntegrationPackages('FigafIRTinfrastructure')</id>
<title type="text">IntegrationPackages</title>
<updated>2024-08-08T07:45:12.669Z</updated>
<category term="com.sap.hci.api.IntegrationPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>
<link href="IntegrationPackages('FigafIRTinfrastructure')" rel="edit" title="IntegrationPackage"/>
<link href="IntegrationPackages('FigafIRTinfrastructure')/$value" rel="edit-media" type="application/octet-stream"/>
<link href="IntegrationPackages('FigafIRTinfrastructure')/IntegrationDesigntimeArtifacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/IntegrationDesigntimeArtifacts" title="IntegrationDesigntimeArtifacts" type="application/atom+xml;type=feed"/>
<link href="IntegrationPackages('FigafIRTinfrastructure')/ValueMappingDesigntimeArtifacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ValueMappingDesigntimeArtifacts" title="ValueMappingDesigntimeArtifacts" type="application/atom+xml;type=feed"/>
<link href="IntegrationPackages('FigafIRTinfrastructure')/MessageMappingDesigntimeArtifacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/MessageMappingDesigntimeArtifacts" title="MessageMappingDesigntimeArtifacts" type="application/atom+xml;type=feed"/>
<link href="IntegrationPackages('FigafIRTinfrastructure')/ScriptCollectionDesigntimeArtifacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ScriptCollectionDesigntimeArtifacts" title="ScriptCollectionDesigntimeArtifacts" type="application/atom+xml;type=feed"/>
<link href="IntegrationPackages('FigafIRTinfrastructure')/CustomTags" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CustomTags" title="CustomTags" type="application/atom+xml;type=feed"/>
<content type="application/octet-stream" src="IntegrationPackages('FigafIRTinfrastructure')/$value"/>
<m:properties>
<d:Id>FigafIRTinfrastructure</d:Id>
<d:Name>Connector for Figaf DevOps Tool</d:Name>
<d:ResourceId>e003061ff4e0460e84e0d8a23219e840</d:ResourceId>
<d:Description><p>The package contains iflows that are used with by Figaf DevOps Tool to iflows required to test and monitor SAP Integration Suite - &nbsp;Cloud Integration</p> <p>Figaf DevOps Tool is a tool to simplify the operation of the SAP Integration Suite.&nbsp;</p> <ul> <li>It has transport capabilities that simplify the operation, governance, and configuration of objects</li> <li>Testing of iflows where you can easily create test cases from your iflows. It supports testing with auto-created mock endpoints</li> <li>Git integration so all iflows are synchronized into the repository making it easier to develop&nbsp;</li> <li>Alerting and monitoring solutions to help improve the delivery process.&nbsp;</li> </ul> <p>&nbsp;The iflows in the package help with the process.&nbsp;</p> <p>You can signup for a free trial at <a href="https://figaf.com/figaf-devops-tool/" rel="nofollow">Figaf</a> you can get started in as little as 30 minutes.&nbsp;</p> <p>The installation guide for the <a href="https://help.figaf.com/portal/en/kb/articles/installation" rel="nofollow">Figaf Tool is here</a>.</p></d:Description>
<d:ShortText>Test and monitor SAP Integration Suite - Cloud Integration with Figaf DevOps Tool. The Script collection is used for the migration process.</d:ShortText>
<d:Version>2304</d:Version>
<d:Vendor>Figaf ApS</d:Vendor>
<d:PartnerContent>true</d:PartnerContent>
<d:UpdateAvailable>false</d:UpdateAvailable>
<d:Mode>READ_ONLY</d:Mode>
<d:SupportedPlatform>Cloud Integration</d:SupportedPlatform>
<d:ModifiedBy>ralf.zimmerningkat@svlfg.de</d:ModifiedBy>
<d:CreationDate>1722934400430</d:CreationDate>
<d:ModifiedDate>1722934400436</d:ModifiedDate>
<d:CreatedBy>ralf.zimmerningkat@svlfg.de</d:CreatedBy>
<d:Products>FigafDevOpsTool,SAPCloudPlatformAPIManagement,SAPCloudPlatformIntegration,SAPCloudPlatformIntegrationSuite,SAPProcessOrchestration</d:Products>
<d:Keywords>automation,governace,monitoring,testing</d:Keywords>
<d:Countries/>
<d:Industries/>
<d:LineOfBusiness/>
<d:PackageContent m:null="true"/>
</m:properties>
</entry>
<entry>
<id>https://trial-3nudqf4g.it-cpitrial05.cfapps.us10-001.hana.ondemand.com:443/api/v1/IntegrationPackages('LSVCustomScripts')</id>
<title type="text">IntegrationPackages</title>
<updated>2024-08-08T07:45:12.669Z</updated>
<category term="com.sap.hci.api.IntegrationPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>
<link href="IntegrationPackages('LSVCustomScripts')" rel="edit" title="IntegrationPackage"/>
<link href="IntegrationPackages('LSVCustomScripts')/$value" rel="edit-media" type="application/octet-stream"/>
<link href="IntegrationPackages('LSVCustomScripts')/IntegrationDesigntimeArtifacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/IntegrationDesigntimeArtifacts" title="IntegrationDesigntimeArtifacts" type="application/atom+xml;type=feed"/>
<link href="IntegrationPackages('LSVCustomScripts')/ValueMappingDesigntimeArtifacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ValueMappingDesigntimeArtifacts" title="ValueMappingDesigntimeArtifacts" type="application/atom+xml;type=feed"/>
<link href="IntegrationPackages('LSVCustomScripts')/MessageMappingDesigntimeArtifacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/MessageMappingDesigntimeArtifacts" title="MessageMappingDesigntimeArtifacts" type="application/atom+xml;type=feed"/>
<link href="IntegrationPackages('LSVCustomScripts')/ScriptCollectionDesigntimeArtifacts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ScriptCollectionDesigntimeArtifacts" title="ScriptCollectionDesigntimeArtifacts" type="application/atom+xml;type=feed"/>
<link href="IntegrationPackages('LSVCustomScripts')/CustomTags" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/CustomTags" title="CustomTags" type="application/atom+xml;type=feed"/>
<content type="application/octet-stream" src="IntegrationPackages('LSVCustomScripts')/$value"/>
<m:properties>
```

**Comment by mwittrock** [comment]
Hi Ralf

If your password contains special characters, it probably should be wrapped in double quotes: -password "like this".

In the next version, you can directly use a service key to authenticate, which is a lot easier to manage. That also means you don't need to provide the hostname, since it's already in the key.

Closing the issue now. Have fun with CPILint!

Regards,

Morten

**Comment by mwittrock** [comment]
Aaaand forgot to close :-)
